version: '3.8'

networks:
  backend:
    driver: "bridge"

services:
  web:
    build:
      context: ../
      dockerfile: ./.docker/app/Dockerfile
    volumes:
      - ../:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
    tty: true
    networks:
      - backend
  db:
    build: ./db
    volumes:
      - ./db/data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
    restart: always
    tty: true
    networks:
      - backend
