version: '3.8'

networks:
  backend:
    driver: "bridge"

services:
  web:
    build:
      context: ../app
      dockerfile: ./.docker/app/Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../:/usr/src/app/
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    restart: always
    networks:
      - backend
  db:
    build: ./db
    volumes:
      - ./db/data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod.db
    restart: always
    networks:
      - backend
  nginx:
    build:
      context: ../
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
